# Site settings
title:       Progressive Solemnity	
email:       adam.michael.wood@gmail.com
author:      Adam Michael Wood
description: "Liturgy at the intersection of tradition and today."
baseurl:     ""
url:         "http://progressivesolemnity.org"

# Google analytics
google_analytics: "UA-46189469-3"

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons: false
github_username: adammichaelwood
facebook: wood.adam.michael
stackoverflow_id:
twitter_username:
google_plus_id: AdamWoodAMW
linkedin_username: 
angellist_username:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: true
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     kramdown
permalink:    pretty
paginate:     3
sass:
  compressed: true
